### ISSUE TITLE
[Feature] Highlight line breaks

### ISSUE THREAD

**Issue by hobarrera** [plasticboy/vim-markdown#140]
Line breaks in markdown are two trailing spaces, which are pretty hard to see, generally.
I would be useful to subtly highlight pairs of trailing spaces in each line. go quickly see these.

**Comment by shirosaki** [comment]
I'm using `molokai` and have same issue.
As an alternative `Visual` seems to change background color for any default themes.

    hi link mkdLineBreak Visual

**Comment by oblitum** [comment]
Wouldn't this be much nicer if it followed [vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) and used [conceal with carriage return character ↵](https://github.com/vim-pandoc/vim-pandoc-syntax/blob/5056e635ecf406e65d7d28651bab55600dd18741/syntax/pandoc.vim#L41)?
