### ISSUE TITLE
filetype=mkd instead of filetype=markdown breaks vim-liquid

### ISSUE THREAD

**Issue by nybblr** [plasticboy/vim-markdown#159]
I use [vim-liquid](https://github.com/tpope/vim-liquid) to get nicely formatted YAML frontmatter in my markdown posts, and occasionally the liquid helpers are handy when I use Jekyll to write a blog post.

While vim-liquid delegates highlighting to other syntaxes, it looks for `syntax/markdown`. This plugin (to prevent collision?) uses the `mkd` type, so unfortunately the nice benefits of this plugin are lost whenever I use frontmatter.

Are there reasons for `mkd` instead of `markdown`? Would it break things to switch over to `markdown`, or perhaps provide a flag to let folks decide to override the default `syntax/markdown`?

**Comment by cirosantilli** [comment]
This also causes other problems, e.g. https://github.com/plasticboy/vim-markdown/pull/114

Maybe it is to avoid conflict with the default Markdown type? I don't know.

cc. @plasticboy

**Comment by plasticboy** [comment]
I can't remember having any particular rationale for mkd, I probably just thought using the file extension made sense. I have no objection to changing it.

**Comment by nybblr** [comment]
Excellent, I'll put together a PR.

**Comment by nybblr** [comment]
Here: https://github.com/plasticboy/vim-markdown/pull/161
