### ISSUE TITLE
YAML frontmatter recognised as level-2 heading

### ISSUE THREAD

**Issue by matatk** [plasticboy/vim-markdown#160]
Using the following markdown file, the last line of the YAML frontmatter is recognised as a level-2 heading.

```markdown
---
layout: article
title: A test of the heading folding when there is YAML frontmatter
tags: markdonw yaml vim-markdonw
---
When I open this file, there is a fold on line 4, as it is assumed that this is a
level-2 heading.  I would expect to find no folds in this document.
```

I have got `let g:vim_markdown_frontmatter=1` in my .vimrc.

**Comment by cirosantilli** [comment]
Ideally solved together with: https://github.com/plasticboy/vim-markdown/issues/148
