### ISSUE TITLE
How to open the :Toc panel on document load?

### ISSUE THREAD

**Issue by matatk** [plasticboy/vim-markdown#166]
I would like to open the Table of Contents when any Markdown file is loaded; I have the following in my .vimrc:

```vim
autocmd FileType mkd :Toc
```

When vim is launched to edit a Markdown file, this doesn't work -- no ToC appears and I don't receive any error messages (though when I type :Toc it does appear).  When a new tab is opened within a running vim instance to edit a Markdown file, this does work and the ToC panel appears.

Most of my Markdown-related .vimrc stuff uses the filetype 'markdown' rather than 'mkd' but I thought using 'mkd' would be better here, as it's the name that this extension uses.

I’ve tried reading around this and noticed things about `<Plug>` and the like, but am not really sure how to use them -- if you could provide any advice it would be appreciated.

**Comment by francozappa** [comment]
Hi all,

Is there a way to open the `:Toc` panel on the left instead of the right ?

**Comment by shirosaki** [comment]
@francozappa with this patch the panel is on the left.

```patch
diff --git a/ftplugin/markdown.vim b/ftplugin/markdown.vim
index 752aee4..6f8adef 100644
--- a/ftplugin/markdown.vim
+++ b/ftplugin/markdown.vim
@@ -344,7 +344,7 @@ function! s:Toc(...)
     if l:window_type ==# 'horizontal'
         lopen
     elseif l:window_type ==# 'vertical'
-        vertical lopen
+        vertical topleft lopen
         " auto-fit toc window when possible to shrink it
         if (&columns/2) > l:header_max_len && g:vim_markdown_toc_autofit == 1
             execute 'vertical resize ' . (l:header_max_len + 1)
```

**Comment by shirosaki** [comment]
The :Toc panel on document load works with the following setting in .vimrc.

```vim
function! s:Toc()
  if &filetype == 'markdown'
    :Toc
  endif
endfunction
autocmd BufWinEnter * call s:Toc()
```

**Comment by matatk** [comment]
@shirosaki Thanks for posting that code -- unfortunately however, I still get the same problem as described in my original post on this thread: the ToC panel does not open automatically for the first Markdown file that I edit in Vim, though I can issue `:Toc` manually and it will appear.  When I `:tabedit` a second Markdown file, then the ToC *does* appear automatically for that file.

I am now using `markdown` as the filetype universally, and this does appear to be set correctly even when the first Markdown file is edited.

**Comment by shirosaki** [comment]
`autocmd FileType markdown :Toc` won't work for the first file because `Filetype` event is executed *before* `ftplugin/markdown.vim` is loaded and `:Toc` is defined there.
`BufWinEnter` event works for the first file.

**Comment by matatk** [comment]
@shirosaki thank you for the explanation. I did try your `BufWinEnter` code yesterday, but unfortunately it does not work for me.  `BufWinEnter` does not work for the first file.

I will try to produce some debugging information later this weekend -- would running `vim -V` be sufficient to debug this?

**Comment by shirosaki** [comment]
You can use `echom` to confirm the function is called or not.
`:message` prints the output.

```vim
function! s:Toc()
    echom 'BufWinEnter'
    if &filetype == 'markdown'
        :Toc                                                                                                                                                                       
    endif
endfunction
autocmd BufWinEnter * call s:Toc()
```

There might be conflicts with other plugins.
https://github.com/plasticboy/vim-markdown/issues/238#issuecomment-167959343

**Comment by matatk** [comment]
@shirosaki thanks.  I have changed my code to the following and have an interesting result...

```vim
function! s:Toc()
       echom 'Markdown ToC outer'
       if &filetype == 'markdown'
               echom 'Markdown ToC inner'
               :Toc
       endif
endfunction
autocmd BufWinEnter * call s:Toc()
```

When I edit a non-markdown file I see "Markdown ToC outer".  When I edit a Markdown file I see "Markdown ToC inner" -- but the ToC does not appear.

I have got Syntastic (and other plugins) installed (using Vundle; Syntactic is listed first).  I ran a recursive `grep` of my `~/.vim` for `Toc` and found only the one defined by this plugin, so it does not look like I am experiencing a conflict.

If I call `:Toc` manually, I see "Markdown ToC outer" twice (presumably not "inner" because it is opening a new window for the ToC, which is plain text rather than Markdown?), and then the ToC appears and works fine.

**Comment by shirosaki** [comment]
I was able to reproduce that with syntactic installed.
It seems that that there are conflicts with `autcocmd * BufEnter` of syntastic.
Syntactic closes Toc window in the event. 
If I remove autocmd setting of syntastic, Toc appears.

```vim
function! s:Toc()
    if &filetype == 'markdown'                                                                                                                                                      
        autocmd! syntastic BufEnter
        :Toc
    endif
endfunction
autocmd BufWinEnter *.m* call s:Toc()
```

**Comment by matatk** [comment]
@shirosaki I think this *almost* fixes it!  The ToC now does appear on document load, but the cursor is not placed inside the ToC window (so I can't directly navigate to the heading I want to jump to).  When I issue `:Toc` normally, the cursor *is* placed inside of the ToC window that appears.

Is there a way to modify the above code to ensure that the cursor will be within the ToC window when the document opens?

I really appreciate your help with all of this and I hope that it will be of use for future users who may also have Syntastic installed.

**Comment by shirosaki** [comment]
The following setting seems to work.
Only with `BufWinEnter` the cursor is not within Toc window for some reason.
Toc window opens without `autocmd! syntastic BufEnter`  and Toc window is closed by Enter key press with syntastic installed.

```vim
function! s:Toc()
  if &filetype == 'markdown'
    :Toc
    set filetype=qf
    setl nofoldenable
    syntax on
  endif
endfunction
autocmd VimEnter *.m*  call s:Toc()
autocmd BufReadPost *.m* call s:Toc()
autocmd BufWinEnter *.m* call s:Toc()
```

**Comment by matatk** [comment]
@shirosaki I've tried the above code and it works perfectly for me too; many thanks for all of your help with this!

**Comment by ErrorTzy** [comment]
> The following setting seems to work. Only with `BufWinEnter` the cursor is not within Toc window for some reason. Toc window opens without `autocmd! syntastic BufEnter` and Toc window is closed by Enter key press with syntastic installed.
> 
> ```viml
> function! s:Toc()
>   if &filetype == 'markdown'
>     :Toc
>     set filetype=qf
>     setl nofoldenable
>     syntax on
>   endif
> endfunction
> autocmd VimEnter *.m*  call s:Toc()
> autocmd BufReadPost *.m* call s:Toc()
> autocmd BufWinEnter *.m* call s:Toc()
> ```

This script works perfectly, except when you create a file without any headings (i.e. a new file). In this case, the markdown file itself will be set to qf type, which mess up the syntax highlight. (As mentioned in #349 ). Therefore I did some modification:

```

function! s:Toc()
  if &filetype == 'markdown'
    let prev_winnr = winnr()
    :Toc
    if winnr() != prev_winnr
      set filetype=qf
      setl nofoldenable
      syntax on
    endif
  endif
endfunction
autocmd VimEnter *.m*  call s:Toc()
autocmd BufReadPost *.m* call s:Toc()
autocmd BufWinEnter *.m* call s:Toc()

```

This should prevent a headerless markdown file being set to qf.
