### ISSUE TITLE
'nomodifiable' is set for new files after using :Toc[htv]

### ISSUE THREAD

**Issue by sim590** [plasticboy/vim-markdown#169]
**Commit** : 091091f
**Steps to reproduce** : 
1. open a `.md` file ;
2. Use `:Toch[htv]` command and press `Enter` ;
3. Try to open another buffer with another file.

I have to `:set modifiable` to solve this until using `:Toch[htv]` breaks it again. The error seems to be triggered by `ftplugin/mkd.vim|342| set nomodifiable`.

**Comment by cirosantilli** [comment]
Ha! So this is why I sometimes got random `nomodifiable`s
