### ISSUE TITLE
Oneline italics/bolds seems wrong

### ISSUE THREAD

**Issue by sim590** [plasticboy/vim-markdown#172]
Why are **bolds** and *italics* regex matching pattern only on oneline as asked in the issue #164. That last issue wasn't a valid issue for asking too many questions. That's why I've redirected the question about *italics* and **bolds** on oneline. I would expect that this formating :

    **Dolor sagittis tristique. Aenean non pede eget nisl bibendum gravida.
    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
    inceptos himenaeos. Morbi laoreet. Suspendisse potenti. Donec accumsan porta
    felis.** 

    *A nisi aliquet commodo. Suspendisse massa lorem, dignissim at, vehicula et,
    ornare non, libero. Donec molestie, velit quis dictum scelerisque, est.*

would translate to this :

**Dolor sagittis tristique. Aenean non pede eget nisl bibendum gravida.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
inceptos himenaeos. Morbi laoreet. Suspendisse potenti. Donec accumsan porta
felis.** 

*A nisi aliquet commodo. Suspendisse massa lorem, dignissim at, vehicula et,
ornare non, libero. Donec molestie, velit quis dictum scelerisque, est.*

as the default vim's markdown syntax does. Why not ?

**Comment by cirosantilli** [comment]
+1

**Comment by kmARC11** [comment]
+1
