### ISSUE TITLE
Treat *.md files as markdown, out of the box

### ISSUE THREAD

**Issue by apennebaker-ni** [plasticboy/vim-markdown#174]
Please configure the vim-markdown plugin so that out of the box, it automatically treats *.md files as markdown files.

As a mitigation, users have to manually insert `au BufRead,BufNewFile *.md set filetype=markdown` in their `~/.vimrc`.

**Comment by cirosantilli** [comment]
Is this different from: https://github.com/plasticboy/vim-markdown/issues/159 ?
