### ISSUE TITLE
Can this syntax highlighter work with Vimdeck?

### ISSUE THREAD

**Issue by nchase** [plasticboy/vim-markdown#180]
[Vimdeck](https://github.com/tybenz/vimdeck) is a tool that turns a markdown file into nice-looking slides, all while inside of vim.

The syntax highlighting here differs from tpope's markdown syntax highlighter, which Vimdeck implicitly depends on.

The big issue seems to be that the "ascii art"-style headers that Vimdeck generates are throwing off the syntax highlighting here. Here's an example of how it looks:

![with plasticboy/vim-markdown](https://cloud.githubusercontent.com/assets/197309/6321774/5d74357a-bad3-11e4-8059-43a0dc1aa6af.png)

Compare to the same file with tpope's vim-markdown (all other things, e.g. vim colorscheme, terminal settings, are identical):

![with tpope/vim-markdown](https://cloud.githubusercontent.com/assets/197309/6321786/a420120a-bad3-11e4-9661-71524045d5d9.png)

That output comes from a simple markdown file, e.g.
```
LIFECYCLE INTERFACES
====================

Hello World
```

I love this syntax highlighter. Does anyone know what would be necessary to make _this_ markdown syntax highlighter play nicer with Vimdeck?

**Comment by cirosantilli** [comment]
Hello nchase, I didn't know about Vimdeck: it is a fun tool.

I think you should open an issue there instead: that ascii art it not proper markdown, so it makes no sense to highlight it as markdown.

What I think they should do is to change the filetype of the output to something else, like `txt` or better, `vimdeck`.

**Comment by nchase** [comment]
these are great suggestions. thanks @cirosantilli!
