### ISSUE TITLE
Underline in list

### ISSUE THREAD

**Issue by codeHatcher** [plasticboy/vim-markdown#181]
I am not sure why some of these are underlined and some are not. Is this intentional?
![screen region 2015-02-23 at 11 49 25](https://cloud.githubusercontent.com/assets/5360982/6322582/7331617e-bb52-11e4-9bd1-0fafafb32a85.png)

**Comment by cirosantilli** [comment]
Isn't that your spell checker? :)

`underline` is a normal word, but `indiegogo` is not, so it gets underlined as an error.

This plugin turns on spell check intelligently, e.g. links and code won't get marked as wrong, so you should use `<indiegogo.com>` for the URLs.

However the correct URLs need `http`, and will get automatically treated as such even without the `<`. Try:

    - http://kickstarter.com



Or you can just do `:set spell=0` to turn if all off, or add words to the dictionary with `zg`.

For future issues, please provide the input in text form, and also state your color theme and vim version ;)
