### ISSUE TITLE
after installation with vundle commands like :Toc not available

### ISSUE THREAD

**Issue by hgw77** [plasticboy/vim-markdown#182]
I opened a Markdown file like README.md but no markdown command like :Toc are available. It looks like the plugin is not active. Is there something I missed?

**Comment by cirosantilli** [comment]
Hi there,

- do other plugins work with Vundle for you?
- is anything else working from this plugin, or is the problem just for the commands?
- what is the output of `set ft?`? That is the filetype, and this plugin should set it to `mkd`.
- does `set rtp?` contain the path to this plugin? (`~/.vim/bundle/vim-markdown` by default)? It should, as that is how Vundle makes Vim see the plugin.

**Comment by wasabi1809** [comment]
I have the same with pathogen.

Other plug-in works, syntax highlighting work as well, I reckon the issue is only commands.
set ft? gives filetype=mkd
set rtp? shows first the vim-markdown directory and the vim-markdown/after directory last in the list

I have the feeling the plugin does not load but couldn't say for sure.

I am using macvim snapshot 75 (Vim 7.4)

Thanks,
Christian

**Comment by cirosantilli** [comment]
@wasabi1809 please open a separate issue since it's another install method

**Comment by wasabi1809** [comment]
Hello,

I found the issue, I had to add the line :

filetype plugin on

so vim load the plugin...

Regards,
Christian Olivier


On Tue, Jun 16, 2015 at 9:22 PM, Ciro Santilli 六四事件 法轮功 纳米比亚胡海峰 <
notifications@github.com> wrote:

> @wasabi1809 <https://github.com/wasabi1809> please open a separate issue
> since it's another install method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plasticboy/vim-markdown/issues/182#issuecomment-112535401>
> .
>



-- 
Christian OLIVIER

**Comment by tonypujals** [comment]
@wasabi1809 That definitely does **not** solve the problem for me.
