### ISSUE TITLE
Auto Indentation for list happens even if we are outside the list immediately after it.

### ISSUE THREAD

**Issue by himkt** [plasticboy/vim-markdown#198]
Hi.

I think that my problem is related to #126 .

```
*

_ <- cursor is here (I think this is proper)
```
![p](https://cloud.githubusercontent.com/assets/5164000/7290432/a3a77998-e9b9-11e4-923c-20847d2d8853.png)

but
```
* hoge

----_<- cursor is here (I think this is improper)
```
![imp](https://cloud.githubusercontent.com/assets/5164000/7290434/aa0d8cbe-e9b9-11e4-9ae9-3f68d72bf877.png)

In other words, if there is no-empty for list and insert two-enter, I have improper indentation.

Is this deliberate action? Please tell me.

**Comment by cirosantilli** [comment]
It might be related to that, and it might be related to https://github.com/plasticboy/vim-markdown/issues/146 as well. Anyway, it's bad behaviour that should be fixed.

Please try to make the title more descriptive of the actual problem next time, I'll update it ;-)

**Comment by cirosantilli** [comment]
Another minor tip: try to describe the problem as:

- before
- action
- after
- expected after

E.g.:

before:
```
* a

<cursor>
```

Action: `<cr>`

After:

```
* a

   <cursor>
```

Expected after:


```
* a

<cursor>
```

It took me some time to understand the issue ;-)

**Comment by himkt** [comment]
I'm sorry.. I got it.
Thanks for telling !

**Comment by ryanoasis** [comment]
:+1:
