### ISSUE TITLE
Unknown function: netrw#NetrwBrowseX

### ISSUE THREAD

**Issue by bstaint** [plasticboy/vim-markdown#202]
use gx open link will echo:
```
Error detected while processing function <SNR>134_OpenUrlUnderCursor:
line 3:
E117: Unknown function: netrw#NetrwBrowseX
```
I think lastest netrw NetrwBrowseX function renamed BrowseX.

**Comment by sim590** [comment]
Yes ! We have experienced this too on the [quicklink project](https://github.com/christoomey/vim-quicklink). You can fix this by checking if it your vim has the patch that introduced the name change like so:
```vim
if has("patch-7.4.567")
    "new name call
else
    "old name call
endif
```

**Comment by cirosantilli** [comment]
@bstaint can you confirm that @sim590's patch fixes it for you? I've heard of such problems before as well.

**Comment by bstaint** [comment]
Yes, Thanks.

**Comment by cirosantilli** [comment]
Good, I'll push it then.

**Comment by cirosantilli** [comment]
Good. @sim590 do you want to push since it's your fix? If you don't mind, I can also do it. If you do, ping me. Thanks.

**Comment by sim590** [comment]
@cirosantilli I've made a pull request for the fix.
