### ISSUE TITLE
Implement a g:vim_markdown_nogx = 1 configuration variable to disable gx

### ISSUE THREAD

**Issue by serge-stroobandt** [plasticboy/vim-markdown#204]
It would be nice to have a `let g:vim_markdown_nogx = 1` configuration variable in order to disable vim-markdown's `gx` functionality.
That way, one could keep on benefiting of all other vim-markdown functions whilst running once own implementation of `gx`.

**Comment by cirosantilli** [comment]
Thanks for the feedback.

Closing in favour of a more generic issue with proposed solution https://github.com/plasticboy/vim-markdown/issues/206

If that is done, you will be able to add:

    nnoremap <Plug> <Plug>Markdown_OpenUrlUnderCursor

to your `.vimrc` to turn it off.

I have documented the missing hook name `<Plug>Markdown_OpenUrlUnderCursor` at: https://github.com/plasticboy/vim-markdown/pull/205

Out of curiosity, what is the case in which the `gx` of Vim Markdown works worse than the Vim default for you?

Please reopen if you feel the proposed solution is not satisfactory.

**Comment by cirosantilli** [comment]
Done: https://github.com/plasticboy/vim-markdown/pull/207
