### ISSUE TITLE
Fenced blocks with extended info strings breaks all highlighting

### ISSUE THREAD

**Issue by emgeee** [plasticboy/vim-markdown#210]
Using extended code attributes like those described in the (pandoc documentation)[http://pandoc.org/demo/example9/pandocs-markdown.html#extension-fenced_code_attributes] causes the entire rest of the document to be treated as a code block. Example below:

\`\`\` {#mycode .haskell .numberLines startFrom="100"}
  console.log("hello world")
\`\`\`

**Comment by emgeee** [comment]
I'm not really an expert in VIM but if you change the regexes on lines 72, and 74 of https://github.com/plasticboy/vim-markdown/blob/master/syntax/mkd.vim#L72

from `start=/^\s*```\s*[0-9A-Za-z_-]*\s*$/`

to `start=/^\s*```\s*.*\s*$/`

It appears to function properly. I'm not sure if there's some performance implications from using the . matcher but if that's an acceptable solution I'd be happy to throw a PR together.

**Comment by cirosantilli** [comment]
I agree that something should be done in the direction that you point specially because CommonMark approves it: http://spec.commonmark.org/0.19/#code-fence

But we would need to check that there are no further backticks after the:

    ```

as required by commonmark to avoid conflict with inline code blocks.
