### ISSUE TITLE
Ampersands & and greater than > are marked as htmlError when inside lists

### ISSUE THREAD

**Issue by olivertaylor** [plasticboy/vim-markdown#214]
Incorrectly flags ampersands in lists as `htmlError`. The only time ampersands should be flagged as errors is when they're in inside html.

 Example:

    * This & That
    1. This & That

**Comment by cirosantilli** [comment]
Added greater than to the title: I think it's the same rationale there?

**Comment by olivertaylor** [comment]
Agreed
