### ISSUE TITLE
:Toc and other commands does not work when installed using Pathogen on Macvim Snaphot 73

### ISSUE THREAD

**Issue by wasabi1809** [plasticboy/vim-markdown#215]
Other plug-in works, syntax highlighting work as well, I reckon the issue is only commands.
set ft? gives filetype=mkd
set rtp? shows first the vim-markdown directory and the vim-markdown/after directory last in the list

I have the feeling the plugin does not load but couldn't say for sure.

I am using macvim snapshot 75 (Vim 7.4)

Thanks,
Christian

**Comment by shirosaki** [comment]
duplicate #182
