### ISSUE TITLE
The last character inside quoted text has a different syntax highlight than the rest of the quote

### ISSUE THREAD

**Issue by for-coursera** [plasticboy/vim-markdown#233]
Noticed a strange thing, don't know if it's a feature (probably :)) or a bug: the last symbol of a line in a quote (`> tex_t_`) is highlighted differently for some reason -- here's a pic:

![example](http://i.imgur.com/v1B2xn3.png)

As you may see, `.`, `l` and `e` have a different color, while `,` and another `.` are OK (because there's a space after those).

Would be grateful for an advise, what is it? :)

**Comment by cirosantilli** [comment]
Please make titles more precise ;-)

What is your output for:

    :colorscheme

?

I don't reproduce: have can produce a minimal example on a minimal clean environment? https://github.com/cirosantilli/vundle-plugin-tester

The last character gets `mkdLineContine`, while the others are `mkdBlockquote`, but both of these seem to be mapped to Comment color.

**Comment by for-coursera** [comment]
And what exactly `mkdLineContinue` does? As you've just said, the last character is highlighted according to it – I've figured that myself some time ago and then just removed it from `mkdBlockquote` definition... :) (which actually solved the issue) 

Are there any drawbacks possible because of that removal?

**Comment by shirosaki** [comment]
I also cannot reproduce.
`mkdLineContinue` looks meaningless. I think no drawbacks of that removal.

**Comment by for-coursera** [comment]
Thanks. I close it then.
