### ISSUE TITLE
Syntax highlight stops working after a dollar sign $

### ISSUE THREAD

**Issue by anyinlover** [plasticboy/vim-markdown#236]
When I use a $, all the words after $ are highlighted, and can't show other syntax highlight, how to fix it?

**Comment by shirosaki** [comment]
Are you use `let g:vim_markdown_math = 1`? Then remove the setting.
https://github.com/plasticboy/vim-markdown#latex-math

**Comment by cirosantilli** [comment]
Closing as per @shirosaki 's comment.

Please make titles more precise ;-)
