### ISSUE TITLE
Syntax highlighting inside fenced code blocks

### ISSUE THREAD

**Issue by louwers** [plasticboy/vim-markdown#239]
As is said [here](https://github.com/plasticboy/vim-markdown/issues/175#issuecomment-75040550): "*[...] actual syntax highlighting of the code? That might be hard*". But is it really?

Vim has a built-in functionality to deal with this if I am not mistaken (see `:h syn-include`).

As I see it there are workarounds for the things that might be hard. Instead of only including syntax highlighting files if the markdown code contains the corresponding fenced code block, we could choose to include them all. Also, we could hard-code the start and end matching regex of languages we want to support. 

If these concessions are made it's just a matter of getting [this example](http://vim.wikia.com/wiki/Different_syntax_highlighting_within_regions_of_a_file) to work, which I have been unsuccesful at thus far, but should be doable.

**Comment by citizenmatt** [comment]
See #93

**Comment by louwers** [comment]
That's great!
