### ISSUE TITLE
Allow terminating emphasis on newline

### ISSUE THREAD

**Issue by alexconst** [plasticboy/vim-markdown#249]
Not all of my markdown files are pretty and some of them have unmatched `*` or `_` which lead to large portions of the file having a messed up syntax highlight.
It would be nice to have a user option that allowed terminating emphasis either at matching character or at a newline.

I found how to do it in `vim-markdown/syntax/markdown.vim`.
For example:
~~~
syn region htmlItalic start="\%(^\|\s\)\zs\*\ze[^\\\*\t ]" end="[^\\\*\t ]\zs\(\n\|\*\)\ze\_W" keepend
~~~
With `\*` having been replaced with `\(\n\|\*\)`

I could just simply clone those 6 syntax region lines and wrap then with an if-else, but I was wondering if there was a smarter way to do things. Something like this (which is not working):
~~~
let teonl_pre = "\(\n\|"
let teonl_suf = "\)"
let sre = "[^\\\*\t ]\zs" . teonl_pre . "\*" . teonl_suf . "\ze\_W"
syn region htmlItalic start="\%(^\|\s\)\zs\*\ze[^\\\*\t ]" end=sre keepend
~~~

1) is there a smarter way for doing this?
2) would a PR for this get merged?

**Comment by shirosaki** [comment]
Does replacing with `\(\n\|\*\)` cause any drawbacks?

`:execute` works with string variables.
https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim#L54

**Comment by alexconst** [comment]
Since the implementation/specification is to continue on newline, the drawback is that it wouldn't be accepted upstream and I would have to keep doing merges with my branch in order to keep synced with upstream.

So the code would look like this then:
~~~vim
if get(g:, "vim_markdown_emphasis_stops_at_newline", 0)
    let esanl_pre = '\(\n\|'
    let esanl_suf = '\)'
else
    let esanl_pre = ''
    let esanl_suf = ''
endif
execute 'syn region htmlItalic start="\%(^\|\s\)\zs\*\ze[^\\\*\t ]" end="[^\\\*\t ]\zs' . esanl_pre . '\*' . esanl_suf . '\ze\_W" keepend'
" other five syntax region expressions here...
~~~

Can I submit a PR for this after I update the other expressions and add the tests?

**Comment by shirosaki** [comment]
Thanks for the explanation. I think we can merge that.
