### ISSUE TITLE
How to disable syntax conceal?

### ISSUE THREAD

**Issue by chengyi818** [plasticboy/vim-markdown#253]
when I'm writting my blog,I want to edit the url link clearly.so my .vimrc looks like this:
```
set conceallevel = 0	
```
after source vimrc,markdown still conceal the url link.
Did I make something wrong?THX for help.

**Comment by shirosaki** [comment]
Spaces around `=` doesn't work.
`set conceallevel=0`

You can check current setting:
`:setl conceallevel`
or
`:set conceallevel`

**Comment by chengyi818** [comment]
@shirosaki  Thankyou for help.
According to your instruction,I have already set conceallevel=0 and source it,but it doesn't work.
I use `:set conceallevel` to confirm my action,conceallevel still equal to 2.
If I use `:setl conceallevel=0`,it can temporarily work.

**Comment by shirosaki** [comment]
`conceallevel` is not modified in vim-markdown. Other plugins might set conceallevel=2 if you install some other plugins.

This may help you.
`au FileType markdown setl conceallevel=0`

**Comment by chengyi818** [comment]
@shirosaki Thanks
I have installed plugin `indentLine` which always set conceallevel to 2.
After I change configuration about indentLine,everything is fine.

**Comment by wnear** [comment]
Is there a way to automatically disable syntax conceal when on insert mode, enable on normal mode.

**Comment by alerque** [comment]
@wnear In VIM the `autocmd` system lets you do pretty much anything triggered by pretty much any event. Nothing to do with this plugin specifically, you can set anything you want based on whatever events you want.

**Comment by wnear** [comment]
```
autocmd InsertEnter  *.{markdown,md} set conceallevel=0
autocmd InsertLeave  *.{markdown,md} set conceallevel=2

```

@alerque I add this. It works. But I still have a few thoughts: 
1. this is a pretty fundamental feature, when Someone want to edit the link or image. So it's the markdown plugin's duty to deal with this.
2. the autocmd method isn't so elegant. The perfect layout should be like this:  only the needed part(the img/link/code paragraph the cursor is in) is expanded to the raw format , while other places stay the same.

**Comment by alerque** [comment]
@wnear Both of your points are already the way it work out of the box. You would only need to write your own hooks if you want something _else_. I assumed you wanted to have all conceals shown instead of just the current line when editing. By default conceal is turned off for the current line while in insert mode.

**Comment by aaronkjones** [comment]
> @shirosaki Thanks
> I have installed plugin `indentLine` which always set conceallevel to 2 as default.
> After I change configuration about indentLine,everything is fine.

To disable for the indentLine plugin, `let g:indentLine_conceallevel = 2`

**Comment by antofthy** [comment]
Nothing worked for me until I had BOTH of these....
``` vimrc
  let g:conceallevel = 0
  let g:indentLine_conceallevel = 0
```
But now indent markings no longer work!  Making the whole `indentLine` module sort of useless!

It is all just so stupid!
