### ISSUE TITLE
Syntax highlight not working for ini blocks

### ISSUE THREAD

**Issue by alexconst** [plasticboy/vim-markdown#254]
I'm not getting any syntax highlight for ini blocks:

```ini
[foo]
hello

[bar]
world
```
Syntax highlight works in vim for .ini files.

Any ideas on the cause?

Thanks

**Comment by shirosaki** [comment]
I open .ini file and `:set filetype` shows `filetype=dosini`.
The following is highlighted in .md.

    ```dosini
    [foo]
    hello

    [bar]
    world
    ```

**Comment by alexconst** [comment]
I made a PR, if that's ok with you.

The reason being that other tools do not work with `dosini` and well the file extension is just `.ini`

**Comment by shirosaki** [comment]
Merged.
