### ISSUE TITLE
Variable to enable/disable syntax conceal

### ISSUE THREAD

**Issue by BOACK** [plasticboy/vim-markdown#256]
In README, you recommend to use Vim's standard conceal configuration to disable syntax conceal.
I set `conceallevel=2` for indentLine, but I'd like to disable syntax conceal.
Why don't you make new variable such as `g:markdown_conceal` to enable/disable conceal like `g:tex_conceal`?

**Comment by shirosaki** [comment]
That would require additional work.
Can you submit a pull request if you need?

Here is relevant code.
https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim#L39
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L661

**Comment by shirosaki** [comment]
And here is test code for conceal.
https://github.com/plasticboy/vim-markdown/blob/master/test/syntax.vader#L192

**Comment by BOACK** [comment]
I sent pull request.
https://github.com/plasticboy/vim-markdown/pull/258

Yes, I don't know much about vim script, but I'd like to do like this.

**Comment by shirosaki** [comment]
Committed the fix based on the patch #258.
