### ISSUE TITLE
Pythonic-style folding doesn't fold level 1 headers

### ISSUE THREAD

**Issue by rafaeln** [plasticboy/vim-markdown#262]
If I set `g:vim_markdown_folding_style_pythonic` to 1, I get the folds to include the headers, but only levels 2 and higher actually get folded. So: fol the following file, the image at the end is what I get.

```markdown
# level 1

text

## level 2

text

## level 2

text

# level 1

text

## level 2

text

## level 2

text
```

![screenshot from 2016-02-21 08 04 36](https://cloud.githubusercontent.com/assets/2940362/13202733/7e477b0e-d873-11e5-9902-b95ad7e111d7.png)

Thanks for the great plugin!

**Comment by shirosaki** [comment]
That is the spec. #213 is implemented by @wlonk .

**Comment by wlonk** [comment]
The motivating use-case was for documents with a single L1 heading, which served as a document title. If L1 headings were folded, the entire document would start folded, which was less useful.

**Comment by rafaeln** [comment]
I see, @wlonk. That behavior makes sense. Maybe the documentation could reflect what you told me. Should I edit it and submit the change?

I also initially thought that setting `g:vim_markdown_folding_level` should make a difference, but this last setting only affects anything when `g:vim_markdown_folding_style_pythonic` is set to 0. 

Would it make sense to change the plugin so that when `g:vim_markdown_folding_style_pythonic` was set to 1 `g:vim_markdown_folding_level` were also active, and setting it to 0 would give the behavior I was expecting, namely, folding including level 1 as well? (and then in documents where only the title is first level one can always `zr` to get the current appearance).

If you guys think that spec is reasonable, I could also work on that one.

**Comment by wlonk** [comment]
I'll gladly review any PR (whether it be for documentation, or respecting folding level more deeply), but I won't be able to merge it, I'm afraid. I really do like your folding level suggestion.

Just tag me in, and I'll contribute what feedback I can!

**Comment by shirosaki** [comment]
I think that spec is reasonable. I'll merge PR if you can work for that.
