### ISSUE TITLE
Add option to disable automatic bullet insertion

### ISSUE THREAD

**Issue by louwers** [plasticboy/vim-markdown#264]
```
- foo
- bar[]
```
Press `<CR>`
```
- foo
-bar
[]
```
instead of
```
- foo
- bar
- []
```

With this option, we get to map our desired key for bullet insertion ourselves.  For example, as `<C-CR>` to make bullet insertion more explicit.

**Comment by shirosaki** [comment]
Automatic bullet insertion is implemented using vim `comments` options.
https://github.com/plasticboy/vim-markdown/blob/master/indent/markdown.vim#L8-L13

We could add an option not to set `comments`, `formatoptions` to disable automatic bullet insertion.

**Comment by louwers** [comment]
Seems like something that is worth implementing then :wink: 

I have comment insertion disabled via
```vim
autocmd BufNewFile,BufRead * setlocal formatoptions-=cro
```
but `vim-markdown` re-enables it I suppose.

**Comment by shirosaki** [comment]
The following setting in `.vimrc` works for me.

```
let g:vim_markdown_new_list_item_indent = 0
autocmd BufNewFile,BufRead * setlocal formatoptions-=r
```

Multiple flags with `-=` won't work.
