### ISSUE TITLE
paste in markdown file blocks too much time

### ISSUE THREAD

**Issue by desmond1121** [plasticboy/vim-markdown#266]
After using vim-markdown in my osx vim (version 7.4.1257), it takes so many time blocked to paste paragraphs into a markdown file, do you have any idea why this would happen? 

thanks

**Comment by shirosaki** [comment]
Maybe syntax highlighting is slow.
http://askubuntu.com/questions/221148/vim-struggles-when-copy-pasting-large-blocks-of-text-in-from-an-external-window/223061#223061
`:set syntax=off` may help.

**Comment by wmusial** [comment]
Same issue here. Disabling syntax is not a solution... vim-markdown is a markdown syntax plugin, disabling it means not using it at all.

**Comment by davidjb** [comment]
For anyone finding themselves here, disabling folding solved the issue for me:

```vim
let g:vim_markdown_folding_disabled = 1
```

Pasting just a few hundred lines went from taking minutes to run (and 100% CPU) to half a second and only hitting 50% CPU briefly.

**Comment by zhenglq** [comment]
Same issue here. Disable folding solve the problem

`let g:vim_markdown_folding_disabled = 1`
