### ISSUE TITLE
API support to get all heading?

### ISSUE THREAD

**Issue by rahmatawaludin** [plasticboy/vim-markdown#270]
I really like this plugin. I know I could get TOC by :Toc. But, I find it not as easy as navigating in fzf. Is it possible to provide API to get all heading? This way, I could pass it to fzf..

See:
https://github.com/junegunn/fzf
https://github.com/junegunn/fzf.vim
https://github.com/junegunn/fzf.vim/issues/94

**Comment by shirosaki** [comment]
`getloclist(0)` returns all heading after `:Toc`.
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L364
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L384

**Comment by rahmatawaludin** [comment]
Umm.. I'm new in this. So, I just make `:call getloclist(0)` in my vim command?

**Comment by shirosaki** [comment]
`let list = getloclist(0)`
`:echo list` shows contents.
