### ISSUE TITLE
Math syntax conceal only works if the math block starts with a "\begin{align}" command or similar

### ISSUE THREAD

**Issue by junrrein** [plasticboy/vim-markdown#272]
I have enabled Math block support in Markdown, and I have set the conceallevel in my .vimrc.

While the Math block syntax highlighting works, what doesn't work consistently is the latex syntax concealing.

I'm using the following as an example

```
$This isn't concealed (0 \le 1)$

$ \begin{align} This is concealed (0 \le 1) \end{align} $

$$
This isn't concealed \omega
0 \le 1
$$

$$
\begin{align}
This is concealed \omega
0 \le 1
\end{align}
$$
```

And it's rendered like this:

![captura de pantalla de 2016-03-16 17-07-34](https://cloud.githubusercontent.com/assets/962049/13827105/9ef43c00-eb99-11e5-92b0-0f4e5453924e.png)

As you see, the math syntax only gets concealed if the math is surrounded by \begin{} and \end{} commands (actually only the \begin command triggers concealment). I tested it with \begin{align} and \begin{alignat}, but it doesn't work with \begin{case}.

Is this intended? Are there any other rules for concealing math syntax?

Edit: This issue manifests with both Vim and Neovim, the first at version 7.4 patch 1558, and the second at 0.1.2. I have vim-markdown updated as of right now.

**Comment by shirosaki** [comment]
Not intended.
I changed the way including tex.vim. Please try latest.

**Comment by junrrein** [comment]
It works correctly now.
Thanks for the fast response.
