### ISSUE TITLE
Custom highlighting colors?

### ISSUE THREAD

**Issue by srsudar** [plasticboy/vim-markdown#274]
Is there a way to provide custom highlight colors to the plugin? I use [xoria256](http://www.vim.org/scripts/script.php?script_id=2140) and in general am quite happy with it. For some reason it feels very understated when applied by this plugin. Headers, for instance, are very similar to text color. \*\*bold\*\* with double asterisk doesn't seem to be highlighted it all. 

Can I do this without changing my whole theme? Apologies if I've missed an answer to this somewhere.

I don't have a minimal sample, but here is a screenshot if is of interest.
![screen shot 2016-04-18 at 7 29 05 pm](https://cloud.githubusercontent.com/assets/6362625/14625904/e70de5ec-059b-11e6-83c2-767f2cc558c7.png)

**Comment by shirosaki** [comment]
Try to add settings like the following in `.vimrc`:

```vim
autocmd FileType markdown highlight htmlBold ctermbg=60
```

**Comment by srsudar** [comment]
That does indeed highlight it. It has the odd side effect that the cursor line hides this manual highlighting but not the italic highlighting. Any thoughts on how to mimic italic behavior, where the cursorline doesn't hide bold highlighting?

![screen shot 2016-04-19 at 12 27 26 pm](https://cloud.githubusercontent.com/assets/6362625/14652735/7de1fc2c-062a-11e6-8187-39db725072cb.png)
![screen shot 2016-04-19 at 12 27 31 pm](https://cloud.githubusercontent.com/assets/6362625/14652734/7de1cc16-062a-11e6-8bab-e3c975baaecd.png)

**Comment by shirosaki** [comment]
Italic is not highlighted on my environment. I don't know the reason.
Maybe terminal setting?
The cursorline seems to hide background color normally in vim.

**Comment by spiritphyz** [comment]
I also could not see any colors for headers. I am using the [onedark](https://github.com/joshdick/onedark.vim) 256-color scheme.

Using a hint from another issue, I found that replacing `htmlBold` with `htmlH1` will correctly target the headers. I chose `ctermfg=70` for a green-ish foreground color. Using the directives below will not cause any side effects with the background color on the currently selected line:
```vim
autocmd FileType markdown highlight htmlH1 cterm=none ctermfg=70                
autocmd BufNewFile,BufRead *.md set filetype=markdown
```

References:
 * https://www.reddit.com/r/vim/comments/3vmu1l/markdown_syntax_with_boldcolored_headers/cxpi6be/
 * https://alvinalexander.com/linux/vi-vim-editor-color-scheme-syntax
