### ISSUE TITLE
More precise settings for syntax concealing

### ISSUE THREAD

**Issue by danijar** [plasticboy/vim-markdown#277]
From what I found, it's not possible to disable/enable individual concealing types. For example, I'd like to disable the features that hides image URLs but keep the awesome LaTeX feature that renders `\partial a_3` as `∂ a₃`.

**Comment by shirosaki** [comment]
The following setting disables markdown URL concealing but enables LaTeX concealing.

`.vimrc`:

```vim
let g:vim_markdown_conceal = 0
let g:vim_markdown_math = 1
set conceallevel=2
```

LaTeX feature works in `$`.
```
$ \partial a_3 $
```

**Comment by danijar** [comment]
Thanks

**Comment by sangaline** [comment]
You can also disable both the markdown and markdown math concealment with:

```
let g:tex_conceal = ""
let g:vim_markdown_conceal = 0
let g:vim_markdown_math = 1
```

This allows you to use unmatched brackets in LaTeX without setting `conceallevel` to `0` (which might be an issue if you use indentLine, as in #253).
