### ISSUE TITLE
how to convert multiple lines to markdown list

### ISSUE THREAD

**Issue by jackywu** [plasticboy/vim-markdown#290]
how to convert multiple lines to markdown list？

**Comment by alex-chew** [comment]
If you have a selection, you can prepend each line in the selection with `:'<'>s/^/- /` or `:'<'>s/^/* /` (or whichever bullet character you prefer).

**Comment by jackywu** [comment]
@alex-chew thanks a lot. I'm trying to make your snippets into keymap in vim , but failed unfortunately. 

```
    vnoremap <leader>tu :'<'>s/^/- /<cr>
    vnoremap <leader>to :'<'>s/^/1. /<cr>

```

no effect.

**Comment by alex-chew** [comment]
@jackywu If you're in visual mode, typing `:` will automatically add `'<'>` to the command (see `:help v_:`). So you can simply use:

```vim
vnoremap <leader>tu :s/^/- /<CR>
vnoremap <leader>to :s/^/1. /<CR>
```

This is a little more robust (ignores blank lines, respects indentation, doesn't touch your search history / highlight things with `hlsearch`):

```vim
vnoremap <silent> <leader>tu :call setline('.', substitute(getline('.'), '\(\S\)', '- \1', ""))<CR>
vnoremap <silent> <leader>to :call setline('.', substitute(getline('.'), '\(\S\)', '1. \1', ""))<CR>
```vim

**Comment by jackywu** [comment]
so greate @alex-chew

**Comment by cosmicraga** [comment]
`vnoremap <silent> <leader>to :call setline('.', substitute(getline('.'), '\(\S\)', '1. \1', ""))<CR>
`
This adds 1 to every line instead of increasing by 1. How do I correct it?
