### ISSUE TITLE
Support Pandoc-style YAML frontmatter (which would break the syntax highlighting currently)

### ISSUE THREAD

**Issue by Hexcles** [plasticboy/vim-markdown#295]
#124 added YAML frontmatter support. However, it only recognizes frontmatter surrounded by `---`, e.g.

```

---
title: test

---
```

However, Pandoc also supports a [different style](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block) in addition to the one above, which starts with `---` but ends with `...`:

```

---
title: test
...
```

Currently this second style would break the highlight of the document in a subtle way. It'd be good if we can also support both styles. I'm not sure if this would cause any compatibility issue (or maybe it's not worthwhile to add support for an optional style of a custom extension).

**Comment by shirosaki** [comment]
Adding new option for that feature would be better.
Here is relevant code.
https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim#L120
