### ISSUE TITLE
Indent not being processed

### ISSUE THREAD

**Issue by duckpuppy** [plasticboy/vim-markdown#300]
Inside of a Markdown file, pressing `o` on a list item line does not produce a new list item.

`b:did_indent` for the buffer is set to `1`, but `:setlocal indentexpr` returns `indentexpr=`.  Other vim-markdown specific setlocal variables are set, for example `setlocal foldexpr` returns `foldexpr=Foldexpr_markdown(v:lnum)`.

**Comment by duckpuppy** [comment]
Found a conflict with another plugin: vim-pencil, which overwrites `indentexpr` when initialized.  Closing this issue.

**Comment by shippy** [comment]
@duckpuppy, if I may ask, how have you resolved the vim-pencil/vim-markdown conflict?
