### ISSUE TITLE
No conceal not respected in math mode

### ISSUE THREAD

**Issue by OJFord** [plasticboy/vim-markdown#321]
```vim
let g:vim_markdown_math=1
let g:vim_markdown_conceal=0
```

I just updated, and now TeX math dollars are concealed, and `\epsilon`s, `\neq`s etc. changed to their respective glyphs.

Previously, I had syntax highlighting between dollars and the dollars shown without even needing to specify `g:vim_markdown_conceal=0`; now it seems not to be possible at all?

**Comment by shirosaki** [comment]
Try:

```
let g:tex_conceal = ""
```

See:
https://github.com/plasticboy/vim-markdown/issues/277#issuecomment-283668680
