### ISSUE TITLE
How to enable conceal?

### ISSUE THREAD

**Issue by qazip** [plasticboy/vim-markdown#322]
Hey,

I've `set conceallevel=2` on my init.vim but it's not working. If I do :set conceallevel=2 with the document opened, it does work. What do I need to place in my init.vim to have it enabled by default, for markdown files?

The following does not work:

`let g:vim_markdown_conceal = 1`

**Comment by shirosaki** [comment]
Does other plugin change `conceallevel` setting?

Put `set conceallevel=2` on the bottom of init.vim.

or

```vim
au FileType markdown setl conceallevel=2
```

**Comment by Congee** [comment]
I `set conceallevel=2` and it doesn't work for me either. How should I debug it?
