### ISSUE TITLE
No colorful heighlights in the code block

### ISSUE THREAD

**Issue by CoinCheung** [plasticboy/vim-markdown#357]
I find the words in my code block is colored green in my environment of archlinux xterm vim8.0, but no other colors or key word heighlights. Did I miss some operation or you did not add these feature? If it is my wrong operation, would you please show me some example where the code in the code blocks are colorfully heighlighted?

**Comment by shirosaki** [comment]
Fenced code block syntax highlighting works.
See:
https://github.com/plasticboy/vim-markdown/pull/93
https://github.com/plasticboy/vim-markdown#fenced-code-block-languages
