### ISSUE TITLE
Feature request: support latex math completion in markdown

### ISSUE THREAD

**Issue by znculee** [plasticboy/vim-markdown#384]
As I mentioned in [Issue #1183 of lervag/vimtex](https://github.com/lervag/vimtex/issues/1183), could you support the latex math completion with youcompleteme? I'll really appreciate that!

**Comment by alerque** [comment]
There should be no reason you can't setup YCM to complete anything you want with or without this plugin, but I don't think it should be up to this plugin to _provide_ completion, especially for non Markdown! There are tons of things that can be embeded in Markdown, and I can see how LaTeX Math would be a useful one to complete, but it is outside the scope of this plugin to do so.
