### ISSUE TITLE
Conflict with vim-anyfold

### ISSUE THREAD

**Issue by tterranigma** [plasticboy/vim-markdown#389]
I try to use this plugin together with [vim-anyfold](https://github.com/pseewald/vim-anyfold/). But when I enable the latter, vim-markdown folding stops working.

**Comment by kadrach** [comment]
I work around this by not activating AnyFold for markdown files (given I want vim-markdown to fold).

```viml
" Stolen from https://stackoverflow.com/a/10410590/2503557
let blacklist = ['markdown']                                     
autocmd Filetype * if index(blacklist, &ft) < 0 | AnyFoldActivate
```

**Comment by tterranigma** [comment]
@kadrach I guess this is enough of a solution.
