### ISSUE TITLE
g:vim_markdown_conceal no longer respected for backticks

### ISSUE THREAD

**Issue by bugeats** [plasticboy/vim-markdown#408]
My long standing config:

```
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0
```

After a (recent?) update, I now need to add a new line in order to stop concealing backticks:

```
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_conceal_code_blocks = 0
```

Backticks aren't "code blocks", right?

**Comment by davidjb** [comment]
Seeing the same issue here (with this https://github.com/plasticboy/vim-markdown/commit/68e753f6c3dcfd167ee00f2b5a5e7c7e3db5edd0 revision).  My config matches @bugeats and the backticks were always visible previously with conceal `let g:vim_markdown_conceal = 0`.  

Seems like it's [this commit](https://github.com/plasticboy/vim-markdown/commit/7f17091c09ab1daa4866fa94a8d646b9e3641c1a) that started using the (undocumented) `vim_markdown_conceal_code_blocks` option and no longer using the standard `vim_markdown_conceal` option.  From the [docs](https://github.com/plasticboy/vim-markdown#syntax-concealing), it still reads as though setting `let g:vim_markdown_conceal = 0` should disable _all_ concealing, which is what it was doing prior to that change so something (code or docs) need fixing. 

And yep, backticks are code spans as opposed to code blocks (https://daringfireball.net/projects/markdown/syntax#precode) so if there's going to be an option for concealing _just_ code blocks, it shouldn't apply to backticks.

**Comment by voldikss** [comment]
I also came into this problem and struggled for much time :neckbeard: 
`g:vim_markdown_conceal_code_blocks` should be mentioned in the [doc](https://github.com/plasticboy/vim-markdown/blob/master/doc/vim-markdown.txt) or [README.md](https://github.com/plasticboy/vim-markdown/blob/master/README.md)

**Comment by MrZhang123** [comment]
I add `vim_markdown_conceal_code_blocks ` in my .vimrc , bug link still concealing, others not concealing like \`text\`, do you have this problem ? @voldikss

**Comment by nixpulvis** [comment]
My temporary fix is to add:

```
let g:vim_markdown_conceal_code_blocks = 0
```

These are all my relevant settings atm now:
```
let g:vim_markdown_conceal = 0
let g:vim_markdown_conceal_code_blocks = 0
let g:tex_conceal = 0
let g:vim_markdown_math = 1
let g:vim_markdown_frontmatter = 1
```

**Comment by shirosaki** [comment]
Added `g:vim_markdown_conceal_code_blocks` to document.
