### ISSUE TITLE
Links with a dot in their display name (ie. URL) breaks syntax highlighting for the rest of the file

### ISSUE THREAD

**Issue by nickjj** [plasticboy/vim-markdown#419]
Here's a test case:

```markdown
[http://example.com](http://example.com)

Hello world
```

Produces this visually:

![image](https://user-images.githubusercontent.com/813219/54078133-fbe01000-4290-11e9-8577-6f3ce9b3850c.png)

It's like the first opening bracket gets colored correctly but everything after that gets stuck in an invalid state. If I remove the `.` in `.com` then the syntax coloring gets fixed but that's not a valid workaround.

This is really disruptive because if I put a link let's say 10% down in the file, then the 90% below it is all underlined with no syntax highlighting support.

**Comment by yous** [comment]
The main reason of this problem is the conflict of two syntaxes; `mkdInlineURL` and `mkdLink`. Markdown recognizes URLs in plain text using `mkdInlineURL` and it consumes `]` right after the first `example.com`, so `mkdLink` seems to not find the closing `]`. I recommend you to use `<http://example.com>` syntax instead of writing the same URL twice.

**Comment by nickjj** [comment]
Using `<http://example.com>` works. Only problem is I have 278 markdown files using the broken syntax. It was never an issue using another editor (not trying to start any editor wars, just bringing that up since it's relevant to this discussion).

I suppose I'll slowly migrate to the `<>` syntax since it's better overall (like you said less duplication), but I wonder if `[]()` should still be fixed here?

**Comment by yous** [comment]
I also want it to be fixed. When I change `mkdInlineURL` not to consume `]` for path/querystring/hash fragment (I changed `\S*` to `[^]\s]*`), it seems to work.

``` diff
diff --git a/syntax/markdown.vim b/syntax/markdown.vim
index d8d34ea..995e3c2 100644
--- a/syntax/markdown.vim
+++ b/syntax/markdown.vim
@@ -70,10 +70,10 @@ execute 'syn region mkdLink matchgroup=mkdDelimiter  start="\\\@<!!\?\[\ze[^]\n]
 " Autolink without angle brackets.
 " mkd  inline links:      protocol     optional  user:pass@  sub/domain                    .com, .co.uk, etc         optional port   path/querystring/hash fragment
 "                         ------------ _____________________ ----------------------------- _________________________ ----------------- __
-syn match   mkdInlineURL /https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/
+syn match   mkdInlineURL /https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?[^]\s]*/

 " Autolink with parenthesis.
-syn region  mkdInlineURL matchgroup=mkdDelimiter start="(\(https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*)\)\@=" end=")"
+syn region  mkdInlineURL matchgroup=mkdDelimiter start="(\(https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?[^]\s]*)\)\@=" end=")"

 " Autolink with angle brackets.
 syn region mkdInlineURL matchgroup=mkdDelimiter start="\\\@<!<\ze[a-z][a-z0-9,.-]\{1,22}:\/\/[^> ]*>" end=">"
```

**Comment by nickjj** [comment]
I implemented your patch and can confirm it's working as intended. A bunch of files that were messed up are now colored up nicely. Of course, I don't have any extensive test suite to run this against, but the initial results looks promising, thanks!

**Comment by yous** [comment]
@shirosaki Do you want this do be implemented in this repository? Maybe we can use more strict character set instead of `\S*` and `[^]\s]*`.

**Comment by nickjj** [comment]
Yeah that would be helpful. Right now I've patched it locally and haven't updated the plugin.

**Comment by nickjj** [comment]
Is this still planned to be addressed in this repo?

**Comment by yous** [comment]
I've just made #451.
