### ISSUE TITLE
Unhide fenced block separator

### ISSUE THREAD

**Issue by dealelopez** [plasticboy/vim-markdown#425]
I'd like to see the backticks (```vim) without having to enter with the cursor in the code block. 
Is there an option to unhide the fenced block separator like this?

**Comment by channoh** [comment]
Refer #408. In my case, it's resolved by inserting `let g:vim_markdown_conceal_code_blocks = 0` in my `.vimrc` file.

**Comment by dealelopez** [comment]
Thanks a lot! I didn't find it in the docs.
