### ISSUE TITLE
Is there a way to leave the tab open

### ISSUE THREAD

**Issue by andres-lowrie** [plasticboy/vim-markdown#432]
Firstly let me just say awesome plugin, thank you. ❤️ 

Is there a configuration option or something I can set that will leave the preview window open even after moving to another split or buffer?

What I'm experiencing now is that every time I move my cursor to some other buffer or split in vim, the tab in my browser with the previews closes; I would like for it to stay open since I tend to have a bunch of splits and buffers open at once, and would like to not have to run the `:MarkdownPreview` command every time I switch back to a markdown buffer. 

Thanks in advance

**Comment by yous** [comment]
Is the plugin providing `:MarkdownPreview` either [iamcco/markdown-preview.vim](https://github.com/iamcco/markdown-preview.vim) or [iamcco/markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim)? I don't see `:MarkdownPreview` command in vim-markdown.

Also markdown-preview.nvim seems to provide the option for [auto closing](https://github.com/iamcco/markdown-preview.nvim#install--usage):
``` vim
" set to 1, the nvim will auto close current preview window when change
" from markdown buffer to another buffer
" default: 1
let g:mkdp_auto_close = 1
```
So try `let g:mkdp_auto_close = 0`.

**Comment by andres-lowrie** [comment]
I must have posted to the wrong project 😅 ... my apologies.

I think I can use that setting.

TY
