### ISSUE TITLE
What is the need for insertleave and inrestenter autocommands?

### ISSUE THREAD

**Issue by aranmohyeddin** [plasticboy/vim-markdown#442]
This is really killing me because when I enter and leave insert mode I get all my foldings unfolded and folded again and that's absolutely horrible! So I ended up commenting the corresponding lines from `ftplugin` and `after/ftplugin`.

**Comment by shirosaki** [comment]
That is for syntax highlight of fenced code block.
https://github.com/plasticboy/vim-markdown#fenced-code-block-languages
Lighter way might be possible. For example limit the update only when editing fenced code block.

**Comment by aranmohyeddin** [comment]
How is it that expanding and collapsing the folds is needed for syntax highlighting?
