### ISSUE TITLE
Breaks `j` and `k` navigation

### ISSUE THREAD

**Issue by juanibiapina** [plasticboy/vim-markdown#448]
When the cursor is not in the beginning of a line when navigating with `j`, it won't jump to the correct location after a few milliseconds. Example:

```
Line 1

Line 3
```

If the cursor is on top of `e` on line 1 and you press `j` twice, it goes to `e` on line 3. If you do it slowly, though, it will go to the beginning of the line.

This seems like a bug to me, but I can't find the location to open a PR to fix it.

**Comment by weirane** [comment]
After commenting this line

https://github.com/plasticboy/vim-markdown/blob/0ad3f44c70dde85489ff3c036ffddd2302556692/after/ftplugin/markdown.vim#L169

the problem goes away, but I don't know what side effects it will produce.

**Comment by juanibiapina** [comment]
So `s:MarkdownSetupFolding()` is doing something weird.

**Comment by weirane** [comment]
I think it is `CursorHold,CursorHoldI` that is causing the problem. If you comment everything inside `s:MarkdownSetupFolding()` (lines showed below), the problem still appears.

https://github.com/plasticboy/vim-markdown/blob/0ad3f44c70dde85489ff3c036ffddd2302556692/after/ftplugin/markdown.vim#L155-L161

**Comment by juanibiapina** [comment]
I'm not using this project anymore.
