### ISSUE TITLE
Conceal isn't working?

### ISSUE THREAD

**Issue by dawsoneliasen** [plasticboy/vim-markdown#452]
I tried `set conceallevel=2` both in my vimrc and from command mode, no luck.

**Comment by leonistor** [comment]
Same problem here, the cause is using the builtin vim on OS X Catalina.
`:help conceallevel` specifies "not available when compiled without the |+conceal| feature".
`vim --version` shows
```
Features included (+) or not (-):
...
-conceal           +linebreak         -python3 ...
```

**Comment by dawsoneliasen** [comment]
Thanks, I'm on Catalina as well so this makes sense. Is there any workaround for this? Can I reinstall Vim (and compile from source)? Is there any reason why the Catalina install disabled conceal?

**Comment by leonistor** [comment]
No idea why the guys from Apple chose this, one should ask the culprit revealed by `vim --version`: root@apple.com :wink:
You might want to install vim from homebrew -- as you might with git, or ruby; I ended up using neovim: 
```
feature-compile
- Nvim always includes ALL features, in contrast to Vim (which ships with
  various combinations of 100+ optional features). Think of it as a leaner
  version of Vim's "HUGE" build. This reduces surface area for bugs, and
  removes a common source of confusion and friction for users.
```
P.S. For some good learning materials check [upcase from thoughtbot](https://thoughtbot.com/upcase/onramp-to-vim) and [vimcasts](http://vimcasts.org/episodes/meet-neovim/).

**Comment by dawsoneliasen** [comment]
Thanks a bunch. I'll close this issue as it doesn't really pertain to this repository.
