### ISSUE TITLE
Highlighting of nested links.

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [plasticboy/vim-markdown#48]
the problem

````
![description [with a nested](link) doesn't highlight correctly](image.png)
````

the patch:

````
syn region mkdLink matchgroup=mkdDelimiter      start="\\\@<!\[" end="\]\ze\s*[[(]" contains=@Spell containedin=mkdLink nextgroup=mkdURL,mkdID skipwhite oneline
````

it just adds "containedin=mkdLink" to the original mkdLink region.

not sure if that's correct, i don't have any experience with vim syntax files, but it works for me so far.

**Comment by ain** [comment]
:+1: for a fix. Reproduced.

**Comment by shirosaki** [comment]
That seems to be fixed on master.
