### ISSUE TITLE
Conceal settings are (constantly) overridden by this plug in

### ISSUE THREAD

**Issue by dylan-chong** [plasticboy/vim-markdown#496]
```
setglobal conceallevel=0
# or
set conceallevel=0
# or even
augroup conceal_level
  autocmd!
  autocmd BufEnter * setlocal conceallevel=0
augroup END
```

in the vim RC file does not affect the result - conceal is always set to 2

Also,   inserting the cursor on concealed text does not unconceal it

**Comment by dylan-chong** [comment]
On the note of overriding options, i have `set formatoptions-=t` in my vimrc and it gets overriden

**Comment by dylan-chong** [comment]
Looks like this problem is caused by another plugin as i can disable this vim-markdown from polyglot and the issue persists. will report if i find out which one

**Comment by dylan-chong** [comment]
the offending plugin is `Yggdroot/indentLine`

**Comment by sagardesai0094** [comment]
@dylan-chong ah, looks like I am having the same issue with indentLine. What was the fix?

**Comment by dylan-chong** [comment]
```
set conceallevel=1
set concealcursor=n
let g:indentLine_concealcursor = &concealcursor
let g:indentLine_conceallevel = &conceallevel
```

found it on one of `Yggdroot/indentLine`'s issues

**Comment by hhh1126** [comment]
I'm not using `Yggdroot/indentLine`, and still have this problem.  
I report it to [512](https://github.com/plasticboy/vim-markdown/issues/512)
If anyone knows how to disable this?
