### ISSUE TITLE
highlight FIXME NOTE XXX TODO in md files

### ISSUE THREAD

**Issue by laoshaw** [plasticboy/vim-markdown#507]
since markdown is used to document code these days, is it possible to add support to highlight the typical keywords in md files if I choose to do so: FIXME BUG NOTE XXX TODO etc that is.

**Comment by nvllsvm** [comment]
I've been using this in a custom syntax file (`after/syntax/markdown.vim`)

```
syntax case match

syn match mkdTodo /TODO:\?/ containedin=htmlH[1-6],mkdNonListItemBlock
hi def link mkdTodo  Todo

syntax case ignore
```
