### ISSUE TITLE
RFE: correct folding for headers without following blank line

### ISSUE THREAD

**Issue by azrdev** [plasticboy/vim-markdown#511]
I often write 
~~~md
# title
## header
my paragraph...
~~~

which breaks vim-markdown folding, while this works:

~~~md
# title

# header
text
~~~

**Comment by flw-cn** [comment]
Please describe your problem in detail.
For example, what you expected to get and what you actually got.

**Comment by azrdev** [comment]
I had some headers which were not recognized as such by the folding logic, but I cannot reproduce my problem anymore, all looks sane. Sorry for the noise!
