### ISSUE TITLE
[Feature Request] g:markdown_fenced_languages for all languages 

### ISSUE THREAD

**Issue by Hritik14** [plasticboy/vim-markdown#513]
Hi

I'd really like if vim-markdown would enable syntax highlighting for all languages in code block.
It would be really cool if it could lazily load the syntax highlighting code after there's a code block for that language.

**Comment by flw-cn** [comment]
Are you having any problems?

**Comment by Hritik14** [comment]
Ah! I had installed https://github.com/gabrielelana/vim-markdown and was assuming this one.
Replaced with this project and now everything rocks !
