### ISSUE TITLE
Does the plugin support automatic bullet point insertion?

### ISSUE THREAD

**Issue by dk949** [plasticboy/vim-markdown#561]
There are a some references to automatic insertion of bullet points in the README, but I cannot figure out how to get it to work. 
<br>
Is it possible to do something like this?
```md
* Line 1
```
Hit `enter` (or `o` or some other shortcut or command)
```md
* Line 1
* 
```
The bullet point appears.

Thank you.

**Comment by quanticle** [comment]
For me, hitting `enter` at the end of a bullet point automatically inserts another bullet point under the current one.

For example, if I have:

```
- foo
- bar
```

Hitting enter at the end of `- bar` yields
```
- foo
- bar
- 
```

**Comment by dk949** [comment]
I see. Must be something in my config messing it up. Thanks, I'll close the issue.

**Comment by vindex10** [comment]
Hi! For those who end up here wondering which option in their vimrc may have broken auto-bulleting.

For me this was the problematic part:

```
 augroup nocomment
     autocmd!
     autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
 augroup END
```

I suppose it is commonly used way to disable "auto-commenting" when moving to a new line from the comment:
https://vi.stackexchange.com/questions/1983/how-can-i-get-vim-to-stop-putting-comments-in-front-of-new-lines
