### ISSUE TITLE
parenthesis get highlighted as a link

### ISSUE THREAD

**Issue by rhdunn** [plasticboy/vim-markdown#57]
Given:

    this is a (link-like) test

The `(link-like)` text gets highlighted as a link part of a markdown link even though it does not have the form `[name](url)`.

**Comment by disconsis** [comment]
Bug:
```
[[title](link)]
```
renders as 
```title``` instead of  ```[title]```

Use case: 
```
Issue description in readme [[issue no](link to issue)]
```
