### ISSUE TITLE
Use "markdown" filetype instead of "mkd" (or both)?!

### ISSUE THREAD

**Issue by blueyed** [plasticboy/vim-markdown#64]
The default Vim distribution uses `markdown` for markdown files (setup via filetype.vim).

Is there a specific reason why this plugin uses `mkd` instead?

One workaround might be to use a symlink and provide both variants of specific files (syntax, ...) - still the filetype setup would have to use a specific value, or maybe `markdown.mkd` to match both?!

**Comment by shirosaki** [comment]
Fixed by 0ef08f71f6325e24ede2195f83c6d5fd02bb6a8d
