### ISSUE TITLE
LaTeX math blocks syntax highlight extension.

### ISSUE THREAD

**Issue by cirosantilli** [plasticboy/vim-markdown#98]
Possible syntaxes:

- `$ x^2 $`. Not supported in many Md engines because of conflict with dollar sign, even if `$$` is supported.
- `$$ x^2 $$`
- `\(\)`
- `\[\]`

We would have to decide which to support.

**Comment by xanderdunn** [comment]
I'd love to see this added!

**Comment by cirosantilli** [comment]
@xanderdunn hey there

`$$` and `$` were merged at: https://github.com/plasticboy/vim-markdown/pull/123

I wonder why this did not get auto closed, closing now.

Did you add

    let g:vim_markdown_math=1

to your vimrc?

Or are you talking about `\( \)` ? Feel free to open a separate feature request if so.

**Comment by xanderdunn** [comment]
@cirosantilli This is fantastic, thanks!  I was indeed missing the `vim_markdown_math` setting.

**Comment by andjscott** [comment]
I'm not sure what the `\\\@<!` does (borrowed from the `$$` region matcher) but these seems to work for `\( \)` and `\[ \]`.

``` vimL
  syn region mkdMath matchgroup=mkdDelimiter start="\\\@<!\\(" end="\\)"
  syn region mkdMath matchgroup=mkdDelimiter start="\\\@<!\\\[" end="\\\]"
```
